### ISSUE TITLE
please  check  the input value 

### ISSUE THREAD

**Issue by ghost** [3imed-jaberi/any-to-any#20]
```js
import {convert} from "any-to-any";
const invalid_binary = '23942394234';// binary should be between 0,1

console.log(convert(invalid_binary,2,16)) // return   1AA2
```
it should be return an error, because the input is an  invalid binary

**Comment by 3imed-jaberi** [comment]
Yes, you're right. Thanks for your catch.
I didn't check the passed string content and its relation with the input base number. I will work around it to publish the next version ASAP. 
 I will work around it to publish the next version ASAP.

**Comment by 3imed-jaberi** [comment]
@tom-and-jary you're 2 issues solved!

**Comment by ghost** [comment]
@3imed-jaberi   thank you very much ,
